# Generated by Django 3.1.1 on 2024-05-06 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=255)),
                ('Product_Price', models.FloatField()),
                ('Product_Discription', models.CharField(max_length=1000)),
                ('Product_Stock', models.IntegerField()),
                ('Stock_trush', models.IntegerField()),
                ('Product_Image', models.FileField(upload_to='product_image')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
