# Generated by Django 3.1.1 on 2024-05-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Product_Category',
            field=models.CharField(choices=[('Mens', 'Mens'), ('Womans', 'Womans'), ('Kids', 'Kids')], default='Mens', max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='Product_Category_sub',
            field=models.CharField(choices=[('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('SwimWear', 'SwimWear'), ('Shoes', 'Shoes')], default='Shirts', max_length=20),
        ),
    ]
